# -*- coding: utf-8 -*-
"""Supermart_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fBohZ6rqAoURoLoiWtS0u_oVMI7qhS-v
"""

import pandas as pd
import numpy as np

df = pd.read_csv('Sample - Superstore.csv', encoding="latin1")
df.head()

df.columns

df.columns = df.columns.str.strip().str.lower()
df.columns

df['product name'].unique()

df['order date'] = pd.to_datetime(df['order date'], format='%m/%d/%Y')
df['ship date']  = pd.to_datetime(df['ship date'],  format='%m/%d/%Y')

print(df['order date'].dtype)
print(df['order date'].head(3))

df['year']         = df['order date'].dt.year
df['month']        = df['order date'].dt.month
df['yearmonth']    = df['order date'].dt.to_period('M').astype(str)
df['ship_days']    = (df['ship date'] - df['order date']).dt.days
df['profit_margin'] = df['profit'] / df['sales']

print(df[['order date', 'year', 'month', 'yearmonth', 'ship_days', 'profit_margin']].head(4))

df['IsLoss']       = (df['profit'] < 0).astype(int)
df['HighDiscount'] = (df['discount'] >= 0.5).astype(int)

print(f"Loss rows:          {df['IsLoss'].sum():,}")
print(f"High discount rows: {df['HighDiscount'].sum():,}")
print(f"\nSample loss rows:")
print(df[df['IsLoss'] == 1][['product name', 'sales', 'discount', 'profit']].head(4))

loss_with_disc = df[(df['IsLoss'] == 1) & (df['HighDiscount'] == 1)]
print(f"\nLoss rows that also had high discount: {len(loss_with_disc):,}")
print(f"That's {len(loss_with_disc)/df['IsLoss'].sum()*100:.1f}% of all losses")

str_cols = df.select_dtypes(include='object').columns

for col in str_cols:
    df[col] = df[col].str.strip()

for col in ['region', 'category', 'sub-category', 'segment', 'ship mode']:
    df[col] = df[col].str.title()

print(df[['region', 'category', 'sub-category', 'segment', 'ship mode']].head())

df.to_csv('superstore_cleaned.csv', index=False)
print("Saved superstore_cleaned.csv")